/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagement;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Aya121298
 */
public class Doctor_fillin extends javax.swing.JFrame {

    /**
     * Creates new form Doctor_fillin
     */
    Doctors doctor = new Doctors();
    MyConnection con = new MyConnection();
    public Doctor_fillin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        jSpinField1 = new com.toedter.components.JSpinField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DM_2 = new javax.swing.JLabel();
        MD_2 = new javax.swing.JTextField();
        MDB_1 = new javax.swing.JButton();
        PLB_4 = new javax.swing.JButton();
        DM_3 = new javax.swing.JLabel();
        MD_3 = new javax.swing.JTextField();
        DM_4 = new javax.swing.JLabel();
        MD_4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(185, 138, 185));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));

        jLabel1.setBackground(new java.awt.Color(204, 51, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fill-in Form");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        DM_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DM_2.setForeground(new java.awt.Color(255, 255, 255));
        DM_2.setText("Doctor Name ");

        MD_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MD_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MD_2ActionPerformed(evt);
            }
        });

        MDB_1.setBackground(new java.awt.Color(0, 204, 51));
        MDB_1.setText("Add");
        MDB_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MDB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDB_1ActionPerformed(evt);
            }
        });

        PLB_4.setBackground(new java.awt.Color(255, 0, 0));
        PLB_4.setText("Clear all");
        PLB_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PLB_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLB_4ActionPerformed(evt);
            }
        });

        DM_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DM_3.setForeground(new java.awt.Color(255, 255, 255));
        DM_3.setText("Phone ");

        MD_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MD_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MD_3ActionPerformed(evt);
            }
        });

        DM_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DM_4.setForeground(new java.awt.Color(255, 255, 255));
        DM_4.setText("Room Number");

        MD_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MD_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MD_4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Qualification");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anesthetics", "Accident and emergency (A&E)", "Breast Screening", "Burn Center (Burn Unit or Burns Unit)", "Cardiology", "Coronary Care Unit (CCU)", "Critical Care", "Gastroenterology", "Gynecology", "Health & Safety" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(DM_2)
                            .addComponent(DM_3)
                            .addComponent(DM_4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MD_2)
                            .addComponent(MD_3)
                            .addComponent(MD_4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1)
                                    .addComponent(jComboBox1, 0, 1, Short.MAX_VALUE)))))
                    .addComponent(jLabel2))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(MDB_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PLB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DM_2)
                        .addGap(37, 37, 37)
                        .addComponent(DM_3)
                        .addGap(33, 33, 33)
                        .addComponent(DM_4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MD_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(MD_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(MD_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MDB_1)
                    .addComponent(PLB_4))
                .addGap(142, 142, 142))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MD_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MD_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MD_2ActionPerformed

    private void MDB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDB_1ActionPerformed

        //String Department = jComboBox1.getSelectedItem().toString();
        String DoctorName = MD_2.getText();
        String PhoneNumber = MD_3.getText();
        String RoomNumber = MD_4.getText();
        String Qualification = jComboBox1.getSelectedItem().toString();
        //SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
       // String date = d.format(jDateChooser1.getDate());
       String Email = jTextField1.getText();
        if ( DoctorName.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Enter Information!!!", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {

            if(doctor.AddDoctor(DoctorName,PhoneNumber,RoomNumber,Qualification,Email))
            {
                JOptionPane.showMessageDialog(rootPane, "Doctor Entered", "Empty Fields", JOptionPane.INFORMATION_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Doctor name already exist!!!!", "Empty Fields", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_MDB_1ActionPerformed

    private void PLB_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLB_4ActionPerformed

        MD_2.setText("");
        MD_3.setText("");
        MD_4.setText("");

    }//GEN-LAST:event_PLB_4ActionPerformed

    private void MD_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MD_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MD_3ActionPerformed

    private void MD_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MD_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MD_4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor_fillin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor_fillin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor_fillin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor_fillin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor_fillin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DM_2;
    private javax.swing.JLabel DM_3;
    private javax.swing.JLabel DM_4;
    private javax.swing.JButton MDB_1;
    private javax.swing.JTextField MD_2;
    private javax.swing.JTextField MD_3;
    private javax.swing.JTextField MD_4;
    private javax.swing.JButton PLB_4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
