
package hospitalmanagement;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ManageDoctorsApp extends javax.swing.JFrame {

    Receptionist rep = new Receptionist();
    public ManageDoctorsApp() {
        initComponents();
        
        rep.FillJTableDoctors(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DM_2 = new javax.swing.JLabel();
        MD_2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MDB_2 = new javax.swing.JButton();
        MDB_3 = new javax.swing.JButton();
        PLB_4 = new javax.swing.JButton();
        PLB_5 = new javax.swing.JButton();
        DM_3 = new javax.swing.JLabel();
        MD_3 = new javax.swing.JTextField();
        DM_4 = new javax.swing.JLabel();
        MD_4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(185, 138, 185));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));

        jLabel1.setBackground(new java.awt.Color(204, 51, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doctor Management");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DM_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DM_2.setForeground(new java.awt.Color(255, 255, 255));
        DM_2.setText("Doctor Name ");

        MD_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MD_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MD_2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Doctor Name","Phone Number","Room Number","Qualification","Email","Date"
            }
        )
        // this code stops editing in the table
        {public boolean isCellEditable( int row,int column){
            return false;
        }
        //////////
    }
    );
    jTable1.setColumnSelectionAllowed(true);
    jTable1.setSurrendersFocusOnKeystroke(true);
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);
    jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

    MDB_2.setBackground(new java.awt.Color(0, 204, 51));
    MDB_2.setText("Delete");
    MDB_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    MDB_2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MDB_2ActionPerformed(evt);
        }
    });

    MDB_3.setBackground(new java.awt.Color(232, 232, 4));
    MDB_3.setText("Edit");
    MDB_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    MDB_3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MDB_3ActionPerformed(evt);
        }
    });

    PLB_4.setBackground(new java.awt.Color(255, 0, 0));
    PLB_4.setText("Clear all");
    PLB_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    PLB_4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            PLB_4ActionPerformed(evt);
        }
    });

    PLB_5.setText("Refresh");
    PLB_5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            PLB_5ActionPerformed(evt);
        }
    });

    DM_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    DM_3.setForeground(new java.awt.Color(255, 255, 255));
    DM_3.setText("Phone ");

    MD_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    MD_3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MD_3ActionPerformed(evt);
        }
    });

    DM_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    DM_4.setForeground(new java.awt.Color(255, 255, 255));
    DM_4.setText("Room Number");

    MD_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    MD_4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MD_4ActionPerformed(evt);
        }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("ID");

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 255, 255));

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
    jLabel4.setText("Qualification");

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anesthetics", "Accident and emergency (A&E)", "Breast Screening", "Burn Center (Burn Unit or Burns Unit)", "Cardiology", "Coronary Care Unit (CCU)", "Critical Care", "Gastroenterology", "Gynecology", "Health & Safety" }));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
        }
    });

    jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Date");

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Email");

    jTextField1.setToolTipText("");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DM_2)
                        .addComponent(DM_3)
                        .addComponent(DM_4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(MD_2)
                                            .addComponent(MD_3)
                                            .addComponent(MD_4, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, 0, 1, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(52, 52, 52))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(MDB_3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PLB_4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addComponent(MDB_2)
                    .addGap(70, 70, 70)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PLB_5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(168, 168, 168))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(30, 30, 30)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(DM_2)
                .addComponent(MD_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(31, 31, 31)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(MD_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(DM_3))
            .addGap(27, 27, 27)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(MD_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(DM_4))
            .addGap(37, 37, 37)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(47, 47, 47)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(46, 46, 46)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MDB_3)
                        .addComponent(MDB_2))
                    .addGap(24, 24, 24))
                .addComponent(PLB_4, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(85, 85, 85))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1)
            .addGap(35, 35, 35)
            .addComponent(PLB_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(66, 66, 66))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PLB_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLB_5ActionPerformed
 //clear the table first
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Doctor Name","Phone Number","Room Number","Qualification","Email","Date"}));
         //Fill the table with data 
       rep.FillJTableDoctors(jTable1);
    }//GEN-LAST:event_PLB_5ActionPerformed

    private void PLB_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLB_4ActionPerformed
      
       MD_2.setText("");
       MD_3.setText("");
       MD_4.setText("");
       jTextField1.setText("");
       
       
    }//GEN-LAST:event_PLB_4ActionPerformed

    private void MDB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDB_3ActionPerformed
       
        String DoctorName = MD_2.getText();
        String PhoneNumber = MD_3.getText();
        String RoomNumber = MD_4.getText();
        String Qualification =jComboBox1.getSelectedItem().toString();
       SimpleDateFormat d = new SimpleDateFormat("yyyy-MM-dd");
        String date =d.format(jDateChooser1.getDate());
        String Email = jTextField1.getText();
                if ( DoctorName.trim().equals("")|| PhoneNumber.trim().equals("")|| RoomNumber.trim().equals("")||Email.trim().equals(""))
        {
        JOptionPane.showMessageDialog(rootPane, "Enter Information!!!", "Empty Fields", JOptionPane.WARNING_MESSAGE);   
        }
       else {
           
           try{ 
               int ID = Integer.valueOf(jLabel3.getText());
                if (rep.EditDoctor(ID,DoctorName,PhoneNumber,RoomNumber,Qualification,date,Email))
        {
          JOptionPane.showMessageDialog(rootPane, "Doctors data edited", "Edit Doctors Data", JOptionPane.INFORMATION_MESSAGE);
       
        }
           }
          
         //  else {
           //JOptionPane.showMessageDialog(rootPane, "Patient Data Not Edited", "Error In Editing Patient Data", JOptionPane.ERROR_MESSAGE);
      //  }
            catch(NumberFormatException ex )
            {
          JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter the Doctor's ID(number)", "ERROR IN DOCTOR ID!!!", JOptionPane.ERROR_MESSAGE);
       
            }   
           
           
            
            
        
    }                 
    }//GEN-LAST:event_MDB_3ActionPerformed

    private void MDB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDB_2ActionPerformed

              try {
               int ID = Integer.valueOf(jLabel3.getText());
                if (rep.RemoveDoctor(ID))
        {
          JOptionPane.showMessageDialog(rootPane, "Data is Deleted", "Delete data", JOptionPane.INFORMATION_MESSAGE);
       
        }
        
           else {
            JOptionPane.showMessageDialog(rootPane, " Data Not Deleted", "Error In Deleting  Data", JOptionPane.ERROR_MESSAGE);
        }
                
            }
            catch(NumberFormatException ex )
            {
                
                // remember to remove
          JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter the  ID(number)", "ERROR IN  ID!!!", JOptionPane.ERROR_MESSAGE);
       
            }
        
            
           
    }//GEN-LAST:event_MDB_2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

        int rIndex = jTable1.getSelectedRow();
        jLabel3.setText(model.getValueAt(rIndex,0).toString());
           
        MD_2.setText(model.getValueAt(rIndex, 1).toString());
        MD_3.setText(model.getValueAt(rIndex, 2).toString());
        MD_4.setText(model.getValueAt(rIndex, 3).toString());
        /*try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(rIndex, 4));
            jDateChooser1.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(ManageDoctorsApp.class.getName()).log(Level.SEVERE, null, ex);
        }*/
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void MD_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MD_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MD_2ActionPerformed

    private void MD_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MD_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MD_3ActionPerformed

    private void MD_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MD_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MD_4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDoctorsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDoctorsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDoctorsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDoctorsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDoctorsApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DM_2;
    private javax.swing.JLabel DM_3;
    private javax.swing.JLabel DM_4;
    private javax.swing.JButton MDB_2;
    private javax.swing.JButton MDB_3;
    private javax.swing.JTextField MD_2;
    private javax.swing.JTextField MD_3;
    private javax.swing.JTextField MD_4;
    private javax.swing.JButton PLB_4;
    private javax.swing.JButton PLB_5;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
